### ISSUE TITLE
First coin

### ISSUE THREAD

**Issue by Andrewsopoku** [FndNur1Labs/WayangCli#74]
Thanks for your work. After generating the Genesis hash and putting it in your code and recompiling. How do you get your first coins. ?

**Comment by FndNur1Labs** [comment]
and this can pos you can mining until much more coins and you stake it. so like other pos. different this one have POS, Token and POW system on 1 coin.

**Comment by Andrewsopoku** [comment]
Please why do the coin show at locked and my balance is still zero

On Thu, Dec 21, 2017 at 12:48 AM, Founder Nur1Labs <notifications@github.com

**Comment by FndNur1Labs** [comment]
Screen shoot so i can know to....

for generated you need open simple wallet
